version: '3'
services:
  scrapy:
    build:
      context: ./luxonis
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: luxonis_sreality
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345lux
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - scrapy
    networks:
      - mynetwork

networks:
  mynetwork:
